### ISSUE TITLE
Validation pipe includes "stack" property

### ISSUE THREAD

**Issue by KennFatt** [storyofams/next-api-decorators#319]
**Describe the bug**
The response from validation pipe is including a "stack" property which exposes the server's error stack trace.

**To Reproduce**
1. `CreateUserDto` class
```ts
import { IsIn, IsNumber, IsString } from "class-validator";

export class CreateUserDto {
  @IsString()
  name: string;

  @IsNumber()
  age: number;

  @IsIn(["MALE", "FEMALE"])
  gender: string;
}
```

2. Route method handler
```ts
@Post()
create(@Body(ValidationPipe) body: CreateUserDto) {
  return {};
}
```

3. Simple POST request
```http
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "payload": "unsupported payload"
}
```
The request sent by VSCode's REST Client extension.

4. Response from the server
```http
HTTP/1.1 400 Bad Request
Content-Type: application/json; charset=utf-8
ETag: "6a4-I9/hzpusvz/u/gNa5qAchH+aAMc"
Vary: Accept-Encoding
Content-Encoding: gzip
Date: Wed, 29 Dec 2021 07:26:43 GMT
Connection: close
Transfer-Encoding: chunked

{
  "statusCode": 400,
  "message": "name must be a string",
  "errors": [
    "name must be a string",
    "age must be a number conforming to the specified constraints",
    "gender must be one of the following values: MALE, FEMALE"
  ],
  "stack": "BadRequestException: name must be a string\n    at Object.validateObject (~/code/web/frameworks/nextjs/crash/next-api-decorators/node_modules/@storyofams/next-api-decorators/dist/internals/validateObject.js:26:15)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async ~/code/web/frameworks/nextjs/crash/next-api-decorators/node_modules/@storyofams/next-api-decorators/dist/internals/handler.js:59:25\n    at async Promise.all (index 0)\n    at async UsersController.runMainLayer (~/code/web/frameworks/nextjs/crash/next-api-decorators/node_modules/@storyofams/next-api-decorators/dist/internals/handler.js:41:24)\n    at async UsersController.descriptor.value (~/code/web/frameworks/nextjs/crash/next-api-decorators/node_modules/@storyofams/next-api-decorators/dist/internals/handler.js:105:13)\n    at async Object.apiResolver (~/code/web/frameworks/nextjs/crash/next-api-decorators/node_modules/next/dist/server/api-utils.js:102:9)\n    at async DevServer.handleApiRequest (~/code/web/frameworks/nextjs/crash/next-api-decorators/node_modules/next/dist/server/next-server.js:1064:9)\n    at async Object.fn (~/code/web/frameworks/nextjs/crash/next-api-decorators/node_modules/next/dist/server/next-server.js:951:37)\n    at async Router.execute (~/code/web/frameworks/nextjs/crash/next-api-decorators/node_modules/next/dist/server/router.js:222:32)"
}
```

**Expected behavior**
What I am expecting is that the validation should only return the following properties (like NestJS does):
```js
{
  "statusCode: "",
  "error": "",
  "messages": []
}
```

**Desktop (please complete the following information):**
 - OS: `Linux 5.15.11-arch2-1 #1 SMP PREEMPT Wed, 22 Dec 2021 09:23:54 +0000 x86_64 GNU/Linux`

**Additional context**
Dependencies:
```js
{
  "@storyofams/next-api-decorators": "^1.6.0",
  "next": "12.0.7",
  "class-transformer": "^0.5.1",
  "class-validator": "^0.13.2",
}
```

**Comment by ggurkal** [comment]
Hi @KennFatt,

Thanks for your interest in the library!

The `stack` property is being sent to the client only in development mode (when `NODE_ENV` is `development`) which is the case when you run `yarn dev`. If you build your code and run your project with `yarn start` you will see that the `stack` property is not there in the response.

**Comment by loicnestler** [comment]
Please add this to the docs. (:
