### ISSUE TITLE
An unknown error occurred

### ISSUE THREAD

**Issue by snake-py** [storyofams/next-api-decorators#457]
**Describe the bug**
I copied the code from the tutorial and I am getting the following error:

```
{
    "statusCode": 500,
    "message": "An unknown error occurred.",
    "errors": [
        "An unknown error occurred."
    ],
    "stack": "TypeError: Cannot read property 'length' of undefined\n    at C:\\Users\\vabis\\Desktop\\Playground\\projects\\eq-nft\\node_modules\\@storyofams\\next-api-decorators\\dist\\internals\\handler.js:45:50\n    at Array.map (<anonymous>)\n    at UserHandler.runMainLayer (C:\\Users\\vabis\\Desktop\\Playground\\projects\\eq-nft\\node_modules\\@storyofams\\next-api-decorators\\dist\\internals\\handler.js:41:62)\n    at UserHandler.descriptor.value (C:\\Users\\vabis\\Desktop\\Playground\\projects\\eq-nft\\node_modules\\@storyofams\\next-api-decorators\\dist\\internals\\handler.js:105:32)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Object.apiResolver (C:\\Users\\vabis\\Desktop\\Playground\\projects\\eq-nft\\node_modules\\next\\dist\\server\\api-utils\\node.js:179:9)\n    at async DevServer.runApi (C:\\Users\\vabis\\Desktop\\Playground\\projects\\eq-nft\\node_modules\\next\\dist\\server\\next-server.js:381:9)\n    at async Object.fn (C:\\Users\\vabis\\Desktop\\Playground\\projects\\eq-nft\\node_modules\\next\\dist\\server\\base-server.js:497:37)\n    at async Router.execute (C:\\Users\\vabis\\Desktop\\Playground\\projects\\eq-nft\\node_modules\\next\\dist\\server\\router.js:213:36)\n    at async DevServer.run (C:\\Users\\vabis\\Desktop\\Playground\\projects\\eq-nft\\node_modules\\next\\dist\\server\\base-server.js:630:29)"
}
```

The code:
```ts
import {
  Body,
  createHandler,
  Get,
  HttpCode,
  Post,
  Req,
} from '@storyofams/next-api-decorators';
import { NextApiRequest } from 'next';

class CreateUserInput {
  email!: string;
  fullName!: string;
}

class UserHandler {
  @Post()
  create(@Body() body: CreateUserInput) {
    // Do something with the body
    return `A new user is created with email address "${body.email}"`;
  }
}
export default createHandler(UserHandler);
``` 

node -v  => v14.17.5
npm -v => 6.14.14

**Comment by snake-py** [comment]
Hi yes can do 

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "experimentalDecorators": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@components/*": ["components/*"],
      "@styles/*": ["styles/*"],
      "@hooks/*": ["hooks/*"],
      "@interfaces/*": ["interfaces/*"],
      "@images/*": ["public/images/*"],
      "@content/*": ["content/*"],
      "@lib/*": ["lib/*"],
      "@pages/*": ["pages/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}

```

**Comment by ggurkal** [comment]
Are you using swc or babel?

**Comment by snake-py** [comment]
The error btw only occours for me once I start using the decorator for response or request. The function decorators seem to work.
